### ISSUE TITLE
Circle CIを通す

### ISSUE THREAD

**Issue by taki** [taki/warn-deprecated#3]
bundle installで、以下のエラーが発生する。

```console
#!/bin/bash -eo pipefail
bundle install

Traceback (most recent call last):
	2: from /usr/local/bin/bundle:23:in `<main>'
	1: from /usr/local/lib/ruby/2.6.0/rubygems.rb:302:in `activate_bin_path'
/usr/local/lib/ruby/2.6.0/rubygems.rb:283:in `find_spec_for_exe': Could not find 'bundler' (2.0.1) required by your /home/circleci/project/Gemfile.lock. (Gem::GemNotFoundException)
To update to the latest version installed on your system, run `bundle update --bundler`.
To install the missing version, run `gem install bundler:2.0.1`
Exited with code 1
```

**Comment by taki** [comment]
通った!!!
